### ISSUE TITLE
Better sort on https://picsum.photos/images

### ISSUE THREAD

**Issue by jellehak** [DMarby/picsum-photos#88] opened 2022-02-16 08:43 UTC
The images on this page: https://picsum.photos/images are being sorted in an unnatural way like: 0, 1, 10, 100, 1000, 1001

Probably nicer to sort it 0,1,2,3,..

**Comment by DMarby** [comment] 2022-09-25 23:40
Hi, thank you for creating this issue. 
Closing as this is a duplicate of #79

**Closed by DMarby** 2022-09-25 23:40 UTC
