### ISSUE TITLE
Add type in url parameter for filter

### ISSUE THREAD

**Issue by matbrgz** [DMarby/picsum-photos#108] opened 2024-01-06 00:17 UTC
Certainly! Below is an example of an issue description:

---

**Issue Title:** Add type in url parameter for filter

**Description:**
Currently, the API provides images for various categories without a clear distinction in the URL parameter. It would be beneficial to introduce a `type` parameter in the URL to filter images based on specific categories. This enhancement would enhance usability and make the API more versatile.

**Example Usage:**
1. **Video Game Cover**
   - URL: `https://picsum.photos/image?type=game`

2. **Movie Poster Cover**
   - URL: `https://picsum.photos/image?type=movie`

3. **Album Cover**
   - URL: `https://picsum.photos/image?type=album`

4. **Book Cover**
   - URL: `https://picsum.photos/image?type=book`

5. **Face Image**
   - URL: `https://picsum.photos/image?type=face`

6. **Fashion Picture**
   - URL: `https://picsum.photos/image?type=fashion`

7. **AI Image**
   - URL: `https://picsum.photos/image?type=ai`

8. **Dashboard**
   - URL: `https://picsum.photos/image?type=dashboard`

9. **CRM**
   - URL: `https://picsum.photos/image?type=crm`

10. **Finance**
    - URL: `https://picsum.photos/image?type=finance`

11. **Calendar**
    - URL: `https://picsum.photos/image?type=calendar`

12. **Messenger Landscape**
    - URL: `https://picsum.photos/image?type=messenger`

12. **Messenger Landscape**
    - URL: `https://picsum.photos/image?type=landscape`

**Comment by DMarby** [comment] 2024-01-06 09:55
Hi,

Thank you for opening an issue, we're not currently planning to add this functionality.
Duplicate of #81

**Closed by DMarby** 2024-01-06 09:55 UTC
