### ISSUE TITLE
Missing image #86

### ISSUE THREAD

**Issue by middle-ages** [DMarby/picsum-photos#116] opened 2024-10-04 10:02 UTC
As you can see by getting [this url](https://picsum.photos/id/86/300/200)₁.

`#85` and `#87` are fine, and the _project_ itself is quite useful!

₁ I am assuming identifiers are zero based continuous indexes in some catalog.

**Comment by DMarby** [comment] 2024-10-04 13:36
Duplicate of #110, #102, #83

**Closed as not planned by DMarby** 2024-10-04 13:36 UTC
