### ISSUE TITLE
/images is not sorted numerically

### ISSUE THREAD

**Issue by ZevEisenberg** [DMarby/picsum-photos#64] opened 2020-03-18 21:39 UTC
URL: https://picsum.photos/images

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/464574/77009924-2dc59100-693f-11ea-9205-f720e2a54353.png">

**Expected order:**
0, 1, 2, 3, 4, 5, ... 98, 99, 100, 101, 102, 103, ... 998, 999, 1000, 1001, 1002

**Actual order:**
0, 1, 10, 100, 1000, 1001, 1002

Guessing this is because the sort that's being used to construct that page isn't a numeric-sensitive sort.

**Comment by DMarby** [comment] 2020-03-19 10:09
Hi,

Please look at existing closed issues before opening new ones, this is a duplicate of #54.

This is intended, ID's used to be numbers, but now they are strings and are thus intentionally handled as such.

**Closed by DMarby** 2020-03-19 10:09 UTC

**Comment by ZevEisenberg** [comment] 2020-03-19 15:08
Thanks. I searched old issues, but didn't find that one. I had searched for "sort," and that issue only mentions "order." But when I filed this, I hadn't yet discovered the `/list` API endpoint, which is what I should have been using ❤️
