### ISSUE TITLE
Qurry Phrase to narrow down the random

### ISSUE THREAD

**Issue by torusservices** [DMarby/picsum-photos#114] opened 2024-06-27 11:20 UTC
https://source.unsplash.com/random/?Cryptocurrency

This is how it used to work on source.unsplash^

https://picsum.photos/1920/1080?random/?Cryptocurrency

So I was thinking something like this?

**Comment by DMarby** [comment] 2024-06-27 14:01
Hi,

Thank you for opening an issue, we're not planning on implementing functionality like this currently.
Duplicate of #81

**Closed as not planned by DMarby** 2024-06-27 14:01 UTC
